apiVersion: apps/v1
kind: Deployment
metadata: 
  name: test-deployment
  labels:
    app: test-deployment

spec:
  replicas: 3
  selector:
    matchLabels:  
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - name: nginx-deploy-container  
        image: nginx:1.24
        ports:
        - containerPort: 80