apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-final-rs

spec:
  # 유지할 pod 개수
  #   - 항상 3개의 pod를 유지하겠다.
  replicas: 5

  # 어떤 pod를 관리할 것인지 정의
  #   - pod의 label 기준으로 선택
  selector:
    matchLabels:
      app: nginx-final

  # pod 생성 템플릿
  template:
    metadata:
      name: q1-nginx-replicaset
      labels:
        app: nginx-final
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.25
          ports:
            - containerPort: 80
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "<h1>$(hostname)</h1>" > /usr/share/nginx/html/index.html
              nginx -g 'daemon off;'